### ISSUE TITLE
import os and app?

### ISSUE THREAD

**Issue by scheung38** [brijeshb42/yapper#2]
Do you need to import os and app in yapper.backend.main.controller.py?

```
import os
from application import app
```

```
from flask import render_template, send_from_directory
from . import main_blueprint


@main_blueprint.route('/')
def index():
    return render_template('main/index.html')


@main_blueprint.route('/favicon.ico')
def favicon():
    return send_from_directory(
        os.path.join(app.root_path, 'static'),  <--- Here
        'favicon.ico',
        mimetype='image/vnd.microsoft.icon'
    )
```

Not sure why

```
$ python manage.py test
IOError: [Errno 2] No such file or directory: 
'/Users/seb/PycharmProjects/yapper/logs/logfile.log'

$ python manage.py db init
IOError: [Errno 2] No such file or directory: 
'/Users/seb/PycharmProjects/yapper/logs/logfile.log'
```

Maybe

```
/bin/bash /Users/seb/PycharmProjects/yapper/start.sh
Enter FLASK_ENV(dev, prod, test): dev
dev
/Users/seb/PycharmProjects/yapper/start.sh: line 6: logs/access.log: No such file or directory

Process finished with exit code 1
```

**Comment by brijeshb42** [comment]
There is no need to import anything new in that file. You should first run `yapper/init.sh`. It creates required directories and symlinks. Then you can run tests or init db.

**Comment by scheung38** [comment]
```
pwd
/Users/seb/PycharmProjects/yapper
(pyenv2.7.10)seb (master *) yapper $ bash init.sh 
init.sh: line 1: cd: templates: No such file or directory
ln: bower_components/bower_components: File exists
mkdir: logs: File exists
```

**Comment by brijeshb42** [comment]
Try to run `mkdir templates` before it.

**Comment by scheung38** [comment]
Is this any reason not to add this to the init.sh ?

**Comment by brijeshb42** [comment]
No. I should add this to `init.sh`. Thanks for pointing it out.

**Comment by scheung38** [comment]
gulp clean && gulp
/Users/seb/PycharmProjects/yapper/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');

**Comment by brijeshb42** [comment]
`npm rebuild node-sass`.
If above does not work, then try deleting the existing `/node_modules` directory and running `npm update`.

**Comment by scheung38** [comment]
Got
```
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.1/binding.node
build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/minminsanjose/PycharmProjects/yapper/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/Users/minminsanjose/PycharmProjects/yapper/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/minminsanjose/PycharmProjects/yapper/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.1.1
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
Build failed
```
